name = "StructDatabaseMapping"
uuid = "66daddfc-c305-4fd9-8f84-fb59daccc546"
authors = ["Luciano Rolando Lorenti <lucianolorenti@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pukeko = "8cf91db1-0219-5b69-b551-5a0ff3c32cce"
